In [3]:
import numpy as np

In [4]:
np.__version__

'2.2.2'

In [6]:
np.array([1, 2, 3]), type(np.array([1, 2, 3]))

(array([1, 2, 3]), numpy.ndarray)

In [7]:
np.array([1, 2, 3, "hello"])

array(['1', '2', '3', 'hello'], dtype='<U21')

In [8]:
array = np.array([1, 2, 3])
array, array.dtype

(array([1, 2, 3]), dtype('int64'))

In [9]:
array = np.array([1, 2, 3],dtype=np.int8)
array, array.dtype

(array([1, 2, 3], dtype=int8), dtype('int8'))

In [10]:
2 ** 8

256

In [11]:
2 ** 8 - 1

255

In [12]:
bin(2**8)

'0b100000000'

In [13]:
bin(2 ** 8 - 1)

'0b11111111'

In [16]:
array = np.array([1, 2, 3, 127, -128],dtype=np.int8)
array

array([   1,    2,    3,  127, -128], dtype=int8)

In [20]:
array = np.array([1, 2, 3, 127, -128],dtype=np.int8)
array

array([   1,    2,    3,  127, -128], dtype=int8)

In [22]:
array = np.array([1, 2, 3, 128, ],dtype=np.uint8)
array

array([  1,   2,   3, 128], dtype=uint8)

In [23]:
array = np.array([1, 2, 3, 128, 255],dtype=np.uint8)
array

array([  1,   2,   3, 128, 255], dtype=uint8)

In [24]:
array = np.array([1, 2, 3, 128, 256],dtype=np.uint8)
array

OverflowError: Python integer 256 out of bounds for uint8