In [2]:
import numpy as np

In [3]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [10]:
array.min(), array.max(), min(array), max(array)

(np.int64(10), np.int64(500), np.int64(10), np.int64(500))

In [ ]:
array.sum(), sum(aray)

(np.int64(1338), np.int64(1338))

In [6]:
array.mean()

np.float64(111.5)

In [12]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array.min(), array.argmin()

(np.int64(10), np.int64(3))

In [13]:
array.max(), array.argmax()

(np.int64(500), np.int64(2))

In [14]:
l = [23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30]
l.index(30)

5

In [17]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [18]:
array[array > 100]

array([500, 310, 101, 203])

In [ ]:
array[array > 100]

In [19]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

array([ 23,  41, 500,  10,  40,  30, 310,  20,  30, 101, 203,  30])

In [20]:
array[-1]

np.int64(30)

In [21]:
array[-2:]

array([203,  30])

In [22]:
array[array % 2 == 0]

array([500,  10,  40,  30, 310,  20,  30,  30])

In [25]:
array[(array % 2 == 0) & (array > 50)]

array([500, 310])

In [ ]:
array = np.array([23, 41, 500, 10, 40, 30, 310, 20, 30, 101, 203, 30])
array

In [26]:
array[ (array % 3 == 0) | ( array < 40)]

array([23, 10, 30, 20, 30, 30])