# Este bisect daca
1. Este divizibil cu 400
2. Este divizibil cu 4, dar nu cu 100

In [1]:
import numpy as np

In [2]:
start_year = 1899
stop_year = 2025

In [4]:
array = np.arange(start_year, stop_year)

In [5]:
array[array % 400 == 0 ]

array([2000])

In [6]:
array[(array % 4 == 0) & (array % 100 != 0) ]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2004, 2008, 2012, 2016, 2020, 2024])

In [7]:
array[(array % 400 == 0 ) |  ((array % 4 == 0) & (array % 100 != 0))]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024])

In [8]:
conditia_1 = array % 400 == 0 
conditia_2 = array % 4 == 0
conditia_3 = array % 100 != 0

array[conditia_1  |  (conditia_2 & conditia_3)]



array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024])

In [9]:
divizibile_cu_400 = array % 400 == 0 
divizibile_cu_4 = array % 4 == 0
nedivizibile_cu_100= array % 100 != 0

array[divizibile_cu_400  |  (divizibile_cu_4 & nedivizibile_cu_100)]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024])

In [11]:
divizibile_cu_4

array([False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True])